#!/usr/bin/env python3
"""
Setup script for YouTube AI Automation system
Installs dependencies and configures API credentials
"""

import os
import sys
import json
from pathlib import Path

def setup_env():
    """Create .env file with user inputs"""
    print("\n🎬 YouTube AI Automation Setup\n")
    print("="*60)
    print("Let's configure your API credentials...\n")
    
    env_path = Path(".env")
    
    if env_path.exists():
        response = input(".env file already exists. Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("Skipping .env configuration.\n")
            return
    
    print("\nYou'll need these FREE API keys:")
    print("1. OpenAI API (free $5 credits): https://platform.openai.com")
    print("2. YouTube API: https://console.cloud.google.com")
    print("3. (Optional) ElevenLabs (free tier): https://elevenlabs.io\n")
    
    openai_key = input("Enter OpenAI API Key (or press Enter to skip): ").strip()
    cohere_key = input("Enter Cohere API Key (or press Enter to skip): ").strip()
    elevenlabs_key = input("Enter ElevenLabs API Key (or press Enter to skip): ").strip()
    youtube_channel_id = input("\nEnter YouTube Channel ID (UCcItHjCePEXykLke8QIhqZQ): ").strip() or "UCcItHjCePEXykLke8QIhqZQ"
    
    env_content = f"""# YouTube AI Automation Configuration
# Generated by setup.py

# API Keys
OPENAI_API_KEY={openai_key}
COHERE_API_KEY={cohere_key}
ELEVENLABS_API_KEY={elevenlabs_key}

# YouTube Configuration
YOUTUBE_CHANNEL_ID={youtube_channel_id}
YOUTUBE_CLIENT_ID=
YOUTUBE_CLIENT_SECRET=
YOUTUBE_REFRESH_TOKEN=

# Video Settings
VIDEO_LENGTH_SHORTS=60
VIDEO_LENGTH_LONG=300
VIDEO_QUALITY=1080p
FPS=30

# Schedule
DILY_UPLOAD_TIME=09:00
VIDEOS_PER_DAY=2

# Niche
NICHE=AI & Automation Hacks
TARGET_LANGUAGE=en
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created!\n")

def create_directories():
    """Create required directories"""
    dirs = [
        "output",
        "assets/templates",
        "assets/music",
        "logs",
        "cache"
    ]
    
    for dir_path in dirs:
        Path(dir_path).mkdir(parents=True, exist_ok=True)
    
    print("✅ Directories created!\n")

def setup_youtube_oauth():
    """Guide user through YouTube OAuth setup"""
    print("\n📺 YouTube OAuth Setup\n")
    print("="*60)
    print("To upload videos automatically, we need YouTube permission.\n")
    print("Steps:")
    print("1. Visit: https://console.cloud.google.com")
    print("2. Create new project (or select existing)")
    print("3. Enable 'YouTube Data API v3'")
    print("4. Create OAuth 2.0 credentials (Desktop app)")
    print("5. Download JSON and save as 'youtube_credentials.json' in root\n")
    
    input("Press Enter when you've completed these steps...")
    
    if Path("youtube_credentials.json").exists():
        print("\n✅ youtube_credentials.json found!\n")
    else:
        print("\n⚠️  youtube_credentials.json not found.")
        print("You can add it later before running upload commands.\n")

if __name__ == "__main__":
    try:
        setup_env()
        create_directories()
        setup_youtube_oauth()
        print("\n" + "="*60)
        print("\n🚀 Setup complete!\n")
        print("Next steps:")
        print("1. pip install -r requirements.txt")
        print("2. python main.py test")
        print("3. python main.py create --prompt 'Your prompt'")
        print("4. python main.py schedule (for daily automation)\n")
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
